

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka/    # 注册服务地址
  instance:
    prefer-ip-address: true   #访问的路径变为IP地址
    lease-renewal-interval-in-seconds: 2  #设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 5
    appname: 授权服务 #如果现在超过了5秒的间隔（默认90秒）

server:
  port: 9020
spring:
  profiles:
    active: dev
  application:
    name: service-authorization    # 服务名称
  datasource:
    url: jdbc:mysql://192.168.56.101:3306/spring_cloud?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 888888
    driver-class-name: com.mysql.jdbc.Driver
    db-name: spring_cloud
    type: com.alibaba.druid.pool.DruidDataSource

#  redis:
#    host: 127.0.0.1
#    port: root
#    password: root
mybatis:
  mapper-locations: classpath*:mapper/*.xml
security:
    oauth2:
      resource:
        filter-order: 3
    client:
      client-id: webapp
      client-secret: webapp
      access-token-uri: http://localhost:9020/oauth/access_token
      user-authorizationUri: http://localhost:9020/oauth/authorize
