server:
  port: 9010
  context-path: /
spring:
  application:
    name: service-gateway
  cloud:
    config:
      name: service-gateway
      profile: dev
      uri: http://127.0.0.1:8888
management:
  security:
    enabled: false
endpoints:
  refresh:
    enabled: true


ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000


cola:
  swagger2:
    enable: true
    base-package:
    title : Cola-Cloud
    description: Cola cloud Restful API docs
    termsOfServiceUrl : http://localhost:4000
    version: 1.0
    apiName: Authorization
    apiKeyName: Authorization